---
deployment:
  tasks:
    - export DEPLOYPATH=/home/idey8819/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp past-records.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
    - /bin/cp da.txt $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH